// vi pod1.yml
-----------------------------------------------------------------------
kind: Pod
apiVersion: v1
metadata:
  name: flipkart
spec:
  containers:
    - name: login
      image: nginx
      ports:
       - containerPort: 80
-------------------------------------------------------------------------    
// vi pod2.yml

kind: Pod
apiVersion: v1
metadata:
  name: amazon
spec:
  containers:
    - name: signup
      image: httpd
      ports:
       - containerPort: 80
